name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        elixir_version: [1.6-otp-19, 1.9-otp-22]
    name: mix test (${{ matrix.elixir_version }})
    runs-on: ubuntu-18.04
    container: wojtekmach/elixir:${{ matrix.elixir_version }}-alpine
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: mix test
